packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260527.1'
  - miniflare@4.20260526.0
  - wrangler@4.95.0
